-- AccountType domain check
SELECT COUNT(*) AS bad_account_types
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.GLACCOUNT
WHERE AccountType NOT IN ('A','L','E','R','X');

-- NormalBalance domain check
SELECT COUNT(*) AS bad_normal_balance
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.GLACCOUNT
WHERE NormalBalance NOT IN ('D','C');

-- Parent must exist (self-referential integrity)
SELECT COUNT(*) AS orphan_parents
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.GLACCOUNT c
LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.GLACCOUNT p
  ON p.GLAccountID = c.ParentAccountID
WHERE c.ParentAccountID IS NOT NULL
  AND p.GLAccountID IS NULL;

-- Status domain check
SELECT COUNT(*) AS bad_status
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.BUDGETHEADER
WHERE StatusCode NOT IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','LOCKED','ARCHIVED');

-- Period references exist (informational, since no enforced FKs)
SELECT COUNT(*) AS missing_start_period
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.BUDGETHEADER h
LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.FISCALPERIOD p
  ON p.FiscalPeriodID = h.StartPeriodID
WHERE h.StartPeriodID IS NOT NULL
  AND p.FiscalPeriodID IS NULL;

SELECT COUNT(*) AS missing_end_period
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.BUDGETHEADER h
LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.FISCALPERIOD p
  ON p.FiscalPeriodID = h.EndPeriodID
WHERE h.EndPeriodID IS NOT NULL
  AND p.FiscalPeriodID IS NULL;

SELECT COUNT(*) AS bad_final_amount
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.BUDGETLINEITEM
WHERE FinalAmount IS NOT NULL
  AND FinalAmount <> (OriginalAmount + AdjustedAmount);

-- Natural key duplicates (since UNIQUE isn't enforced)
SELECT BudgetHeaderID, GLAccountID, CostCenterID, FiscalPeriodID, COUNT(*) AS cnt
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.BUDGETLINEITEM
GROUP BY 1,2,3,4
HAVING COUNT(*) > 1
LIMIT 50;

SELECT COUNT(*) AS bad_rule_type
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ALLOCATIONRULE
WHERE RuleType NOT IN ('DIRECT','STEP_DOWN','RECIPROCAL','ACTIVITY_BASED');

SELECT COUNT(*) AS bad_rounding
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ALLOCATIONRULE
WHERE RoundingMethod NOT IN ('NEAREST','UP','DOWN','NONE');

SELECT COUNT(*) AS bad_debit_credit
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.CONSOLIDATIONJOURNALLINE
WHERE (DebitAmount < 0 OR CreditAmount < 0)
   OR (DebitAmount > 0 AND CreditAmount > 0);