SELECT
  BudgetHeaderID,
  BudgetCode,
  BudgetName,
  BudgetType,
  ScenarioType,
  FiscalYear,
  StartPeriodID,
  EndPeriodID,
  BaseBudgetHeaderID,
  StatusCode,
  SubmittedByUserID,
  SubmittedDateTime,
  ApprovedByUserID,
  ApprovedDateTime,
  LockedDateTime,
  IsLocked,
  VersionNumber,
  Notes,
  CAST(ExtendedProperties AS NVARCHAR(MAX)) AS ExtendedProperties,
  CreatedDateTime,
  ModifiedDateTime
FROM Planning.BudgetHeader;
