USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

-- =====================================================================
-- Cost Center Hierarchy Name Path (Snowflake replacement for fn_GetHierarchyPath)
-- =====================================================================

CREATE OR REPLACE VIEW VW_COSTCENTER_NAME_PATH AS
WITH ancestors AS (
  SELECT
    child.COSTCENTERID    AS COSTCENTERID,
    parent.COSTCENTERNAME AS ANCESTOR_NAME,
    parent.HIERARCHY_LEVEL AS ANCESTOR_LEVEL
  FROM COSTCENTER child
  JOIN COSTCENTER parent
    ON child.HIERARCHY_PATH LIKE parent.HIERARCHY_PATH || '%'
)
SELECT
  COSTCENTERID,
  LISTAGG(ANCESTOR_NAME, ' > ')
    WITHIN GROUP (ORDER BY ANCESTOR_LEVEL) AS HIERARCHY_NAME_PATH
FROM ancestors
GROUP BY COSTCENTERID;


-- =====================================================================
-- Snowflake replacement for tvf_ExplodeCostCenterHierarchy
-- Default behavior: all roots, max depth 10, exclude inactive, as-of CURRENT_DATE()
-- =====================================================================

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW VW_COSTCENTER_HIERARCHY_DEFAULT AS
WITH params AS (
  SELECT
    NULL::NUMBER        AS ROOT_COSTCENTER_ID,
    10::NUMBER          AS MAX_DEPTH,
    FALSE::BOOLEAN      AS INCLUDE_INACTIVE,
    CURRENT_DATE()      AS AS_OF_DATE
),
valid_cc AS (
  SELECT cc.*
  FROM COSTCENTER cc, params p
  WHERE (p.INCLUDE_INACTIVE OR cc.ISACTIVE = TRUE)
    AND cc.EFFECTIVEFROMDATE <= p.AS_OF_DATE
    AND (cc.EFFECTIVETODATE IS NULL OR cc.EFFECTIVETODATE >= p.AS_OF_DATE)
),
roots AS (
  SELECT
    v.COSTCENTERID   AS ROOT_ID,
    v.HIERARCHY_PATH AS ROOT_PATH,
    v.HIERARCHY_LEVEL AS ROOT_LEVEL
  FROM valid_cc v, params p
  WHERE (p.ROOT_COSTCENTER_ID IS NULL AND v.PARENTCOSTCENTERID IS NULL)
     OR (p.ROOT_COSTCENTER_ID IS NOT NULL AND v.COSTCENTERID = p.ROOT_COSTCENTER_ID)
),
nodes_raw AS (
  SELECT
    r.ROOT_ID,
    v.COSTCENTERID,
    v.COSTCENTERCODE,
    v.COSTCENTERNAME,
    v.PARENTCOSTCENTERID,
    (v.HIERARCHY_LEVEL - r.ROOT_LEVEL) AS HIERARCHYLEVEL,
    np.HIERARCHY_NAME_PATH             AS HIERARCHYPATH,
    REGEXP_REPLACE(v.HIERARCHY_PATH, '/$', '') AS RAW_ID_PATH,
    v.ALLOCATIONWEIGHT
  FROM roots r
  JOIN valid_cc v
    ON v.HIERARCHY_PATH LIKE r.ROOT_PATH || '%'
  LEFT JOIN VW_COSTCENTER_NAME_PATH np
    ON np.COSTCENTERID = v.COSTCENTERID
),
nodes AS (
  SELECT *
  FROM nodes_raw, params p
  WHERE HIERARCHYLEVEL <= p.MAX_DEPTH
),
sortprep AS (
  -- Turn "/1/3/7" into "0000000001/0000000003/0000000007"
  SELECT
    n.ROOT_ID,
    n.COSTCENTERID,
    n.COSTCENTERCODE,
    n.COSTCENTERNAME,
    n.PARENTCOSTCENTERID,
    n.HIERARCHYLEVEL,
    n.HIERARCHYPATH,
    n.RAW_ID_PATH,
    n.ALLOCATIONWEIGHT,
    LISTAGG(LPAD(f.value::STRING, 10, '0'), '/')
      WITHIN GROUP (ORDER BY f.index) AS SORTPATH
  FROM nodes n,
       LATERAL FLATTEN(input => SPLIT(REGEXP_REPLACE(n.RAW_ID_PATH, '^/|/$', ''), '/')) f
  GROUP BY
    n.ROOT_ID, n.COSTCENTERID, n.COSTCENTERCODE, n.COSTCENTERNAME, n.PARENTCOSTCENTERID,
    n.HIERARCHYLEVEL, n.HIERARCHYPATH, n.RAW_ID_PATH, n.ALLOCATIONWEIGHT
),
child_counts AS (
  SELECT
    PARENTCOSTCENTERID AS COSTCENTERID,
    COUNT(*) AS CHILDCOUNT
  FROM nodes
  WHERE PARENTCOSTCENTERID IS NOT NULL
  GROUP BY 1
),
cum_weight AS (
  SELECT
    child.COSTCENTERID,
    EXP(SUM(LN(NULLIF(parent.ALLOCATIONWEIGHT, 0)))) AS CUMULATIVEWEIGHT
  FROM nodes child
  JOIN nodes parent
    ON child.RAW_ID_PATH LIKE parent.RAW_ID_PATH || '%'
  GROUP BY child.COSTCENTERID
)
SELECT
  s.COSTCENTERID,
  s.COSTCENTERCODE,
  s.COSTCENTERNAME,
  s.PARENTCOSTCENTERID,
  s.HIERARCHYLEVEL,
  s.HIERARCHYPATH,
  s.SORTPATH,
  IFF(COALESCE(cc.CHILDCOUNT, 0) = 0, TRUE, FALSE) AS ISLEAF,
  COALESCE(cc.CHILDCOUNT, 0) AS CHILDCOUNT,
  COALESCE(cw.CUMULATIVEWEIGHT, 1) AS CUMULATIVEWEIGHT
FROM sortprep s
LEFT JOIN child_counts cc ON cc.COSTCENTERID = s.COSTCENTERID
LEFT JOIN cum_weight cw   ON cw.COSTCENTERID = s.COSTCENTERID;
