SELECT 'FISCALPERIOD_RAW'  AS table_name, COUNT(*) AS row_count
FROM SNOWFLAKE_LEARNING_DB.PLANNING_STG.FISCALPERIOD_RAW
UNION ALL
SELECT 'GLACCOUNT_RAW',      COUNT(*) FROM SNOWFLAKE_LEARNING_DB.PLANNING_STG.GLACCOUNT_RAW
UNION ALL
SELECT 'COSTCENTER_RAW',     COUNT(*) FROM SNOWFLAKE_LEARNING_DB.PLANNING_STG.COSTCENTER_RAW
UNION ALL
SELECT 'BUDGETHEADER_RAW',   COUNT(*) FROM SNOWFLAKE_LEARNING_DB.PLANNING_STG.BUDGETHEADER_RAW
UNION ALL
SELECT 'BUDGETLINEITEM_RAW', COUNT(*) FROM SNOWFLAKE_LEARNING_DB.PLANNING_STG.BUDGETLINEITEM_RAW;
