-- Logical constraints declared for documentation and validation purposes.
-- Snowflake does not enforce foreign keys by default.

ALTER TABLE PLANNING.BUDGETHEADER
  ADD CONSTRAINT PK_BUDGETHEADER
  PRIMARY KEY (BudgetHeaderID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT PK_BUDGETLINEITEM
  PRIMARY KEY (BudgetLineItemID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT FK_BLI_BH
  FOREIGN KEY (BudgetHeaderID)
  REFERENCES BUDGETHEADER(BudgetHeaderID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT FK_BLI_CC
  FOREIGN KEY (CostCenterID)
  REFERENCES COSTCENTER(CostCenterID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT FK_BLI_GL
  FOREIGN KEY (GLAccountID)
  REFERENCES GLACCOUNT(GLAccountID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT FK_BLI_FP
  FOREIGN KEY (FiscalPeriodID)
  REFERENCES FISCALPERIOD(FiscalPeriodID);

ALTER TABLE PLANNING.PLANNING.ALLOCATIONRULE
  ADD CONSTRAINT PK_AllocationRule PRIMARY KEY (AllocationRuleID);

ALTER TABLE PLANNING.PLANNING.CONSOLIDATIONJOURNAL
  ADD CONSTRAINT PK_ConsolidationJournal PRIMARY KEY (JournalID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNALLINE
  ADD CONSTRAINT PK_ConsolidationJournalLine PRIMARY KEY (JournalLineID);

ALTER TABLE PLANNING.BUDGETLINEITEM
  ADD CONSTRAINT FK_BLI_BH FOREIGN KEY (BudgetHeaderID) REFERENCES PLANNING.BUDGETHEADER(BudgetHeaderID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNAL
  ADD CONSTRAINT FK_CJ_BH FOREIGN KEY (BudgetHeaderID) REFERENCES PLANNING.BUDGETHEADER(BudgetHeaderID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNAL
  ADD CONSTRAINT FK_CJ_FP FOREIGN KEY (FiscalPeriodID) REFERENCES PLANNING.FISCALPERIOD(FiscalPeriodID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNALLINE
  ADD CONSTRAINT FK_CJL_CJ FOREIGN KEY (JournalID) REFERENCES PLANNING.CONSOLIDATIONJOURNAL(JournalID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNALLINE
  ADD CONSTRAINT FK_CJL_GL FOREIGN KEY (GLAccountID) REFERENCES PLANNING.GLACCOUNT(GLAccountID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNALLINE
  ADD CONSTRAINT FK_CJL_CC FOREIGN KEY (CostCenterID) REFERENCES PLANNING.COSTCENTER(CostCenterID);

ALTER TABLE PLANNING.CONSOLIDATIONJOURNALLINE
  ADD CONSTRAINT FK_CJL_AR FOREIGN KEY (AllocationRuleID) REFERENCES PLANNING.ALLOCATIONRULE(AllocationRuleID);
